### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by chipmanj** [UofUEpiBio/PHS7045-advanced-programming#6]
@UofUEpiBio/phs7045-2023 Homework 1 is live on the website at: [link](https://uofuepibio.github.io/PHS7045-advanced-programming/hw-01-essentialsSimulations.html).  Please use this thread for questions.

**Comment by hyejung0** [comment]
Hi @chipmanj , 
I was working on HW1 and realized that sometimes, the control arm has the biggest posterior probability for all 1000 samples so that by the end, my allocation probabilities are 0 for all 4 arms. For this situation, should I make the allocation probability all equal, meaning, set them to 0.25? I need probabilities greater than 0 for sampling treatment.

**Comment by chipmanj** [comment]
@hyejung0 What do you mean by "biggest posterior probability"?

For the RAR, you'll want to use the probability that each arm is the max.  A way to do this is to repeatedly draw a  sample from each posterior and note how often each arm has the largest draw.

**Comment by chipmanj** [comment]
@UofUEpiBio/phs7045-2023 Hi Class. As mentioned in Thursday's lab, HW 1's deliverable is modified to creating a function for Design 1 and 2.  These functions should use vectorization, and you should modularize your code to reduce redundancy.

**Comment by hyejung0** [comment]
Hi @gvegayon  and @chipmanj  ! 
I have problem with git push at the moment. Here's the message that I get when I push:


----

fatal: The current branch main has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin main

To have this happen automatically for branches without a tracking
upstream, see 'push.autoSetupRemote' in 'git help config'.

-----

When I google about it, it says that it's because I don't have the connection with the GitHub remotely. But I had set it up before. Does it have to do with my SSH thingy?? 

Can you please help me figure it out? 

Meanwhile, I will send my homework1 via email. Thank you!

**Comment by chipmanj** [comment]
@UofUEpiBio/phs7045-2023 Hi Class, I posted my solution to HW 1 to a new private repo: https://github.com/UofUEpiBio/PHS7045-advanced-programming-solutions

Please request access to see the solution.
